import os
PATH = os.getcwd()
DATA_PATH = os.path.join(PATH, 'Data')
OUTPUT_PATH = os.path.join(PATH, 'Output')
KNN_PATH = os.path.join(PATH, 'KNN')
PARA_SELECTION_PATH = os.path.join(PATH, 'Cluster', 'output')
SIMILAR_MATRIX = os.path.join(PATH, 'Similarity', 'output')
POINT_MATRIX = os.path.join(PATH, 'Dimension_Reduction', 'output')
CLUSTER_PATH = os.path.join(PATH, 'Cluster', 'output')
TimeExtraction_PATH = os.path.join(PATH, 'Intensive_Time_Extraction', 'output')
SpaceExtraction_PATH = os.path.join(PATH, 'Intensive_Space_Extraction', 'output')
Hurdat_PATH = os.path.join(PATH, 'Hurdat')
Representative_Trajectory_PATH = os.path.join(PATH, "Representative_Trajectory", "output")
